services:
  syllabus:
    build: .
    image: syllabus-extract
    container_name: syllabus-extract
    working_dir: /app
    command: python3 main.py
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Tokyo
      - YEAR=${YEAR}
